name: hello-world
on: [push]
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
- name: fail-step
        run: exit 1 - name: missing-command
        
